books/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('book/', views.BookListView.as_view(), name='book_list'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('book/<int:pk>/update/', views.book_update, name='book_update'),
    path('book/delete/', views.book_delete, name='book_delete'),
    path('author/', views.AuthorListView.as_view(), name='author_list'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('tag/', views.TagListView.as_view(), name='tag_list'),
    path('tag/<int:pk>/', views.TagDetailView.as_view(), name='tag_detail'),
    path('user/', views.UserListView.as_view(), name='user_list'),
    path('user/<int:pk>/', views.UserDetailView.as_view(), name='user_detail'),
    path('upload/', views.upload, name='upload'),
    path('comment/delete', views.comment_delete, name='comment_delete'),
]

books/models.py
import zipfile
import isbnlib

from xml.etree import ElementTree

from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.files.images import ImageFile

import wikipedia; wikipedia.set_lang(settings.LANGUAGE_CODE[:2])

class EpubParsingException(Exception):
    pass

  
class Author(models.Model):
    name = models.CharField('nom', max_length=200, unique=True)

    def __str__(self):
        return self.name.title()

    def get_absolute_url(self):
        return reverse('author_detail', args=[str(self.pk)])


class Tag(models.Model):
    name = models.CharField('nom', max_length=200, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tag_detail', args=[str(self.pk)])


class Book(models.Model):
    title = models.CharField('titre', max_length=200, default='livre sans nom')
    upload_date = models.DateTimeField("date d'ajout", auto_now_add=True)
    file = models.FileField('Fichier', upload_to='books')
    uploader = models.ForeignKey(User, on_delete=models.PROTECT)

    cover = models.ImageField(upload_to='covers', blank=True, null=True)

    publication_date = models.DateField('date de publication',
                                        blank=True, null=True)
    summary = models.TextField('Résumé', blank=True)

    authors = models.ManyToManyField(Author, verbose_name='authors', blank=True)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title.title()

    def epubjs(self):
        return settings.EPUBJS_URL + self.file.url

    def wikipedia(self):
        results = wikipedia.search('{title}'.format(title=self.title))
        if len(results) > 0:
            page = wikipedia.page(results[0])
            result = page.url
        else:
            result = ""
        return result

    def get_absolute_url(self):
        return reverse('book_detail', args=[str(self.pk)])

    def get_update_url(self):
        return reverse('book_update', args=[str(self.pk)])
      
    def is_commented_by_user(self, user):
        for comment in self.comment_set.all():
            if comment.user == user:
                return True
        return False
    
    def likers(self):
        return [c.user for c in Comment.objects.filter(book=self) if c.recommended]

    def haters(self):
        return [c.user for c in Comment.objects.filter(book=self) if not c.recommended]

    def extract_metadata_from_epub(self):

        ns = {
            'n': 'urn:oasis:names:tc:opendocument:xmlns:container',
            'pkg': 'http://www.idpf.org/2007/opf',
            'dc': 'http://purl.org/dc/elements/1.1/'
        }

        try:
            z = zipfile.ZipFile(open(self.file.path, 'rb'))
        except zipfile.BadZipFile as e:
            raise EpubParsingException(e)

        # locate OPF file
        txt = z.read('META-INF/container.xml')
        tree = ElementTree.fromstring(txt)
        cfname = tree.find('n:rootfiles/n:rootfile', namespaces=ns)

        if cfname is None:
            raise EpubParsingException("epub root file not found")

        # find metadata
        cf = z.read(cfname.attrib['full-path'])
        tree = ElementTree.fromstring(cf)
        p = tree.find('./pkg:metadata', namespaces=ns)

        # repackage the data
        self.title = getattr(p.find('dc:title', ns), 'text', '').lower()
        author_name = getattr(p.find('dc:creator', ns), 'text', '').lower()
        if author_name:
            author, created = Author.objects.get_or_create(name=author_name)
            if created:
                author.save()
            self.authors.set([author])
        # self.authors = [Author(getattr(p.find('dc:creator', ns), 'text'))]

        # # try ISBN
        # isbn = getattr(p.find('dc:identifier', ns), 'text')
        # try:
        #     isbn_res = isbnlib.meta(isbn)
        # except isbnlib._exceptions.NotValidISBNError:
        # else:
        #     self.isbn = isbn
        #     self.authors = [Author(name) for name in isbn_res['Authors']]

        # extract cover
        m = tree.find('./pkg:manifest', namespaces=ns)
        for item in m:
            if item.attrib['id'] == 'cover-id':
                cover_url = item.attrib['href']
                print(z.open('OEBPS/' + cover_url))
                cover = ImageFile(file=z.open('OEBPS/' + cover_url))
                self.cover = cover


class Comment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    date = models.DateTimeField("date d'ajout", auto_now_add=True)

    content = models.TextField('Commentaire')
    recommended = models.BooleanField('Je recommande')

    def get_absolute_url(self):
        return reverse('book_detail', args=[str(self.book.pk)])

    def __str__(self):
        return 'commentaire de {user} sur {book}'.format(user=self.user, book=self.book)

books/forms.py
from django import forms
from django_select2.forms import Select2TagWidget, Select2TagMixin, HeavySelect2TagWidget

from .models import Book, Author, Tag, Comment

class DateInput(forms.DateInput):
    input_type = 'date'

class Select2TagWidgetWithSpaces(Select2TagWidget):
    def build_attrs(self, *args, **kwargs):
        """Add select2's tag attributes."""
        self.attrs.setdefault('data-minimum-input-length', 1)
        self.attrs.setdefault('data-tags', 'true')
        self.attrs.setdefault('data-token-separators', '[","]')
        return super(Select2TagMixin, self).build_attrs(*args, **kwargs)


class UploadFileForm(forms.Form):
    file = forms.FileField()


class BookUpdateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields=('title', 'summary', 'publication_date', 'authors', 'tags', 'cover')
        widgets={'publication_date': DateInput,
                 'authors': Select2TagWidgetWithSpaces,
                 'tags': Select2TagWidget}

    authors = forms.ModelMultipleChoiceField(queryset=Author.objects.all(),
                                             to_field_name='name',
                                             widget=Select2TagWidgetWithSpaces,
                                             required=False)
    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
                                          to_field_name='name',
                                          widget=Select2TagWidget,
                                          required=False)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', 'recommended')

books/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.shortcuts import render
from django.urls import reverse
from django.forms.models import modelform_factory

from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from django_select2.forms import Select2TagWidget

from .models import Book, Author, Tag, EpubParsingException, Comment
from .forms import (UploadFileForm, DateInput, Select2TagWidgetWithSpaces,
                    BookUpdateForm, CommentCreateForm)


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'books/index.html'

    def get_queryset(self):
        return Book.objects.order_by('-upload_date')[:5]
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['nav_active'] = 'index'
        context['comment_list'] = Comment.objects.order_by('-date')[:5]
        return context


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book

    def get_queryset(self):
        return Book.objects.order_by('title')

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['nav_active'] = 'book_list'
        return context


class BookDetailView(LoginRequiredMixin,
                     generic.edit.CreateView,
                     generic.DetailView):
    model = Book
    form_class = CommentCreateForm
    template_name = 'books/book_detail.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.book = generic.DetailView.get_object(self)
        obj.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['is_commented_by_current_user'] = generic.DetailView.get_object(self).is_commented_by_user(self.request.user)
        return context


@login_required
def comment_delete(request):
    comment = Comment.objects.get(pk=request.POST['comment_id'])
    comment.delete()
    return HttpResponseRedirect(reverse('book_detail', args=[comment.book.id]))


class BookUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Book
    form_class = BookUpdateForm

@login_required
def book_delete(request):
    book = Book.objects.get(pk=request.POST['book_id'])
    book.delete()
    return HttpResponseRedirect(reverse('index'))

@login_required
def book_update(request, pk):
    book = Book.objects.get(pk=pk)
    if request.method == 'POST':
        form = BookUpdateForm(request.POST, request.FILES, instance=book)
        for field, cls in (('authors', Author) ,('tags', Tag)):
            for value in form[field].value():
                lvalue = value.lower()
                instance, created = cls.objects.get_or_create(name=lvalue)
                if created:
                    print("Created", instance)
                    instance.save()
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('book_detail',
                                        args=[book.id]))
    else:
        form = BookUpdateForm(instance=book)
    return render(request, 'books/book_form.html',
                  {'form': form, 'book': book})


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author

    def get_queryset(self):
        # return Author.objects.all().order_by('name')
        return Author.objects.filter(book__isnull=False).order_by('name').distinct()

    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        context['nav_active'] = 'author_list'
        return context


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


class TagListView(LoginRequiredMixin, generic.ListView):
    model = Tag


class TagDetailView(LoginRequiredMixin, generic.DetailView):
    model = Tag


class UserListView(LoginRequiredMixin, generic.ListView):
    model = User


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = User


@login_required
def upload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            book = Book(file=request.FILES['file'],
                        uploader=request.user)
            book.save()
            try:
                book.extract_metadata_from_epub()
            except EpubParsingException as e:
                messages.error(request, "Pas réussi à lire les métadonnées du fichier : " + str(e))
            else:
                book.save()
            return HttpResponseRedirect(reverse('book_update',
                                        args=[book.id]))
    else:
        form = UploadFileForm()
    return render(request, 'books/upload.html', {'form': form, 'nav_active': 'upload'})

books/templates/books/author_detail.html
{% extends "layout.html" %}
{% block content %}
<h1> {{ author }} </h1>
{% include "books/book_list_widget.html" with book_list=author.book_set.all %}

<!-- <ul>
{% for book in author.book_set.all %}
<li><a href="{% url 'book_detail' book.id %}">{{ book }}</a></li>
{% endfor %}
</ul> -->
{% endblock %}

books/templates/books/author_list.html
{% extends "layout.html" %}
{% block content %}
<h1>Tous les auteurs</h1>
<hr />
<ul>
{% for author in author_list %}
    <li>
        <a href="{% url 'author_detail' author.id %}">{{ author }}</a>
        ({{ author.book_set.all|length }} livre{% if author.book_set.all|length > 1 %}s{% endif %})
    </li>
{% endfor %}
</ul>
{% endblock %}

books/templates/books/book_detail.html
{% extends "layout.html" %}
{% load bootstrap4 %}
{% load fontawesome %}
<!-- -->
{% block head %}{{ form.media.css }}{% endblock %}
<!-- -->
{% block content %}

<div class="book-detail">
  <div class="book-detail-cover">
    {% if book.cover %}
    <img src="{{ book.cover.url }}" class="img-fluid img-rounded img-thumbnail" />
    {% endif %}
  </div>

  <div class="book-detail-content">
    <h1>{{ book }}</h1>

    {% if book.summary %}
    <p>{{ book.summary|linebreaks }}</p>
    {% endif %}

    <h6>
      {% fontawesome_icon 'edit' %} Écrit par
      {% for author in book.authors.all %}
          <a href="{{ author.get_absolute_url }}">{{ author }}</a>{% include "books/comma.html" %}
      {% endfor %}
    </h6>

    <h6>
      {% fontawesome_icon 'user' %} Proposé par
      <a href="{% url 'user_detail' book.uploader.id %}">
        {{ book.uploader }}
      </a>
    </h6>

    {% if book.publication_date %}
    <h6>
      {% fontawesome_icon 'calendar' %} Publié en {{ book.publication_date|date:"Y" }}
    </h6>
    {% endif %}

    <h6>
      {% fontawesome_icon 'calendar' %} Ajouté le {{ book.upload_date|date }}
    </h6>

    {% include "books/likes_widget.html" %}

    <p>
      {% for tag in book.tags.all %}
        <a href="{{ tag.get_absolute_url }}" class="badge badge-secondary">{{ tag }}</a>
      {% endfor %}
    </p>

    <a href="{{ book.get_update_url }}" class="btn btn-secondary">
      {% fontawesome_icon 'edit' %} Modifier
    </a>
    <a href="{{ book.epubjs }}" target="_blank" class="btn btn-info">
      {% fontawesome_icon 'book' %} Lire
    </a>
    <a href="{{ book.file.url }}" class="btn btn-success">
      {% fontawesome_icon 'download' %} Télécharger
    </a>
  </div>
</div>

<hr />
<h2>Commentaire{{ book.comment_set.all|pluralize }}</h2>
{% for comment in book.comment_set.all %}
    <a name="#comment-{{ comment.id }}"></a>
    <p>
        {% if comment.recommended %}
            {% fontawesome_icon 'thumbs-up' color='green' large=True %} Recommandé 
        {% else %}
            {% fontawesome_icon 'thumbs-down' color='red' large=True %} Déconseillé 
        {% endif %}
        par {{ comment.user }}, le {{ comment.date|date }}
            {% if comment.user == user %}
            <button data-toggle="modal" data-target="#confirmationModal"
                    class="btn btn-danger btn-sm">
            {% fontawesome_icon 'trash' %}
            </button>
            <form action="{% url 'comment_delete' %}" method='POST' id="comment_delete_form">
                {% csrf_token %}
                <input type="hidden" name="comment_id" value="{{ comment.id }}" />
            </form>
            {% include "books/modal_confirmation.html" with obj=comment form="comment_delete_form" %}
        {% endif %}
    </p>
    {{ comment.content|linebreaks }}
{% empty %}
    Pas encore de commentaire
{% endfor %}

{% if not is_commented_by_current_user %}
    <hr />
    <h2>Laisser un commentaire</h2>
    <form action="{% url 'book_detail' book.id %}" method='POST' id='comment_form'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">
        Valider
    </button>
{% endif %}

{% endblock %}

books/templates/books/book_form.html
{% extends "layout.html" %}
{% load bootstrap4 %}
{% load fontawesome %}
{% block head %}{{ form.media.css }}{% endblock %}
{% block content %}
<h1>Éditer un livre</h1>
<form action="{% url 'book_update' book.id %}" method='POST' id='book_form'
      enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_form form %}
<a class="btn btn-secondary" href="{% url 'book_detail' book.id %}">{% fontawesome_icon 'ban' %} Annuler</a>
<button type="submit" class="btn btn-success" onclick="lowerConvert()">
    {% fontawesome_icon 'check' %} Valider
</button>
<span data-toggle="modal" data-target="#confirmationModal"
        class="btn btn-danger">
    {% fontawesome_icon 'trash' %} Supprimer
</span>
</form>
<form action="{% url 'book_delete' %}" method='POST' id="book_delete_form">
    {% csrf_token %}
    <input type="hidden" name="book_id" value="{{ book.id }}" />
</form>
{% include "books/modal_confirmation.html" with obj=book form="book_delete_form" %}

{% endblock %}
{% block footer %}
{{ form.media.js }}
<script type="text/javascript">
  function lowerConvert() {
    fields = ["id_authors", "id_tags"];
    for (var f in fields) {
      coll = document.getElementById(fields[f]).options;
      for (var k in coll) {
        val = coll[k].value;
        if (typeof(val) != "undefined") {
          coll[k].value = val.toLowerCase();
        }
      }
    }
    //get the form id and submit it
    var form = document.getElementById("book_form");
    form.submit();
  }
</script>
{% endblock %}

books/templates/books/book_list.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
<h1>Tous les livres</h1>
<hr />
</div>
<div class="row">
{% include "books/book_list_widget.html" %}
</div>
{% endblock %}

books/templates/books/book_list_widget.html
{% load fontawesome %}
<div class="book-list">
  {% for book in book_list %}
  <div class="book-list-item
              {% if onerow %}
              {% if forloop.counter > 2 and forloop.counter <= 3 %} d-none d-md-flex
              {% elif forloop.counter > 3 and forloop.counter <= 4 %} d-none d-lg-flex
              {% elif forloop.counter > 4 %} d-none d-xl-flex {% endif %}
              {% endif %}">
    {% if book.cover %}
    <a href="{{ book.get_absolute_url }}">
      <img class="book-list-item-cover" src="{{ book.cover.url }}" />
    </a>
    {% endif %}
    <div class="book-list-item-body">
      <a href="{{ book.get_absolute_url }}">
        <h5 class="book-list-item-title">{{ book }}</h5>
      </a>
      <!-- <h6 class="card-subtitle mb-2 text-muted">{{ book.upload_date }}</h6> -->
      <p>
        {% for tag in book.tags.all %}
        <a href="{{ tag.get_absolute_url }}" class="tag">{{ tag }}</a>
        {% endfor %}
      </p>
      <p class="book-list-item-summary">{{ book.summary|truncatechars:100 }}</p>
    </div>
    <div class="book-list-item-footer">
      {% include "books/likes_widget.html" %}
      <div class="float-right">
        <a href="{{ book.get_absolute_url }}" class="btn btn-primary btn-sm"
          data-toggle="tooltip" title="Détails">
          {% fontawesome_icon 'info-circle' %}
        </a>
        <a href="{{ book.file.url }}" class="btn btn-success btn-sm"
           data-toggle="tooltip" title="Télécharger">
          {% fontawesome_icon 'download' %}
        </a>
      </div>
    </div>
  </div>
  {% comment %} {% if forloop.counter|divisibleby:2 %}
    <div class="w-100 d-none d-sm-block d-md-none"></div>
  {% endif %}
  {% if forloop.counter|divisibleby:3 %}
    <div class="w-100 d-none d-md-block d-lg-none"></div>
  {% endif %}
  {% if forloop.counter|divisibleby:4 %}
    <div class="w-100 d-none d-lg-block d-xl-none"></div>
  {% endif %}
  {% if forloop.counter|divisibleby:5 %}
    <div class="w-100 d-none d-xl-block"></div>
  {% endif %} {% endcomment %}
  {% endfor %}
</div>

books/templates/books/comma.html
{% if not forloop.last %}{% ifequal forloop.revcounter 2 %} et {% else %}, {% endifequal %}{% else %}{% endif %}

books/templates/books/comment_list_widget.html
{% load fontawesome %}
<div class="card-deck">
  {% for comment in comment_list %}
  <div class="card">
    {% if comment.book.cover %}
    <a href="{{ comment.book.get_absolute_url }}#comment-{{comment.id}}">
      <img class="card-img-top" src="{{ comment.book.cover.url }}" style="width:100%; object-fit: cover; object-position: center; max-height: 100px;" />
    </a>
    {% endif %}
    <div class="card-body">
      <h5 class="card-title">
        <a href="{{ comment.book.get_absolute_url }}#comment-{{comment.id}}">
          {{ comment.book }}
        </a>
      </h5>
      <h6 class="card-subtitle mb-2 text-muted">
        {% if comment.recommended %}
          {% fontawesome_icon 'thumbs-up' %}
        {% else %}
          {% fontawesome_icon 'thumbs-down' %}
        {% endif %}
        {{ comment.user }}
      </h6>
      <p class="card-text">{{ comment.content|truncatechars:100 }}</p>
    </div>
  </div>
  {% endfor %}
</div>

books/templates/books/index.html
{% extends "layout.html" %} {% load fontawesome %}
<!-- -->
{% block content %}
<div class="row">
    <h1>Bienvenue</h1>
</div>
<hr />
<div class="row">
    <h2>{% fontawesome_icon 'book' %} Derniers livres</h2>
</div>
<div class="row">
    {% include "books/book_list_widget.html" with onerow='true' %}
</div>
<hr />
<div class="row">
    <h2>{% fontawesome_icon 'comments' %} Derniers commentaires</h2>
</div>
<div class="row">
    {% include "books/comment_list_widget.html" %}
</div>
{% endblock %}

books/templates/books/likes_widget.html
{% load fontawesome %}
{% if book.likers %}
  <span data-toggle="tooltip" class="like"
     title="{{ book.likers|join:", "|truncatechars:50 }}">
    <span class="fa fa-thumbs-up"></span>
    {{ book.likers|length }}
  </span>
{% endif %}
{% if book.haters %}
  <span data-toggle="tooltip" class="like"
     title="{{ book.haters|join:", "|truncatechars:50 }}">
    <span class="fa fa-thumbs-down"></span>
    {{ book.haters|length }}
  </span>
{% endif %}

books/templates/books/modal_confirmation.html
<div class="modal fade" id="confirmationModal"
     tabindex="-1" role="dialog"
     aria-labelledby="confirmationModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="confirmationModalLabel">Confirmation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Êtes-vous certain de vouloir supprimer <span class="font-italic">{{ obj }}</span> ?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
              Annuler
          </button>
          <button type="button" class="btn btn-primary btn-danger"
             onclick="var form = document.getElementById('{{ form }}'); form.submit();">
              Supprimer
          </button>
        </div>
      </div>
    </div>
  </div>

books/templates/books/tag_detail.html
{% extends "layout.html" %}
{% block content %}
<h1>Livres taggés {{ tag }}</h1>
{% include "books/book_list_widget.html" with book_list=tag.book_set.all %}
{% endblock %}

books/templates/books/tag_list.html
{% extends "layout.html" %}
{% block content %}
<h1>Tous les tags</h1>
<hr />
<ul>
{% for tag in tag_list %}
    <li>
        <a href="{% url 'tag_detail' tag.id %}">{{ tag }}</a>
        ({{ tag.book_set.all|length }} livre{% if tag.book_set.all|length > 1 %}s{% endif %})
    </li>
{% endfor %}
</ul>
{% endblock %}

books/templates/books/upload.html
{% extends "layout.html" %}
{% load bootstrap4 %}
{% block content %}
<h1>Ajouter un livre</h1>
<form action="{% url 'upload' %}" method='POST' enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_form form %}
<button type="submit" class="btn btn-success">
    Envoyer
</button>
</form>
{% endblock %}